config/routes.rb
Rails.application.routes.draw do

  get '/' => 'pages#index'
  get '/sessions/new' => 'sessions#new', as: "new_session"
  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'
  get '/session_helper' => 'pages#session_helper'

  resources :users, :guesses, :rounds

  resources :decks do
    resources :cards
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  has_many :guesses

  validates :question, :answer, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  has_many :rounds

  validates :name, presence: true

  def last_round
    {
    at: self.rounds.last.created_at.in_time_zone("America/Chicago").strftime("%m/%d/%Y at %I:%M %p"),
    correct: self.rounds.last.correct_guesses,
    guesses: self.rounds.last.guesses.count
    }
  end
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :round
  belongs_to :card
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :user
  belongs_to :deck
  has_many :guesses

  def correct_guesses
    guesses_by_card = self.guesses.group_by{ |guess| guess.card_id }
    guesses_by_card.select { |card| guesses_by_card[card].length == 1 }.length
  end

  def total_guesses
    self.guesses.count
  end

  def when_played
    self.updated_at.localtime
  end

  def card_arr
    self.deck.cards
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rounds

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: /.+@\D*\.\D{3}\z/ }
  validates :password, length: { minimum: 6 }, allow_nil: false

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @card = Card.find(params[:id])
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index

  end

  def show
    session[:round_id] = nil
    session[:deck_id] = params[:id]
    redirect_to new_round_path
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

  def new
  end

  def create
    @guess = Guess.create(guess_params)
    # if @card.answer.downcase == params[:answer].downcase
    #   @correct = true
    #   session[:cards].delete(@card.id)
    # else
    #   @correct = false
    #   session[:cards].rotate!
    # end
    # erb :'cards/response'
  end

    private
    def guess_params
      params.require(:guess).permit(:card_id, :round_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def session_helper
    @uniqueword22 = session.inspect
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

  def new
    @round = Round.new
    @round.deck = Deck.find(session[:deck_id])
    if logged_in?
      @round.user = current_user
    else
      @round.user = User.find(1)
    end
    @round.save
    session[:round_id] = @round.id
    @card = @round.card_arr.first
    redirect_to deck_card_path(session[:deck_id], @card)
  end

  # def show
  #   @round = Round.find(session[:round_id])
  #   if @round.card_arr.empty?
  #     redirect_to current_user
  #   else
  #     @card = Card.find(@round.card_arr.first)
  #     render 'cards#show'
  #   end
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.id
      redirect_to user_path(@user)
    else
      @errors = ["Your shit ain't right"]
      render "new"
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params[:user]).permit(:email, :password)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/'
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:current_user_id]) if session[:current_user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/views/cards/show.html.erb
<h1>here is a card</h1>
<%= @card.question %>

<%= form_tag(guess_path, method: "post") do %>
  <%= hidden_field_tag :card_id, value: @card.id %>
  <%= label_tag :answer %>
  <%= text_field_tag :answer %>
  <%= submit_tag "Submit Guess" %>
<% end %>

app/views/decks/_deck.html.erb
<p><strong><%= link_to deck.name, deck_path(deck) %></strong></p>

app/views/decks/index.html.erb
<h2>Decks...</h2>
<%= render Deck.all %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
  </head>

  <body>
    <nav>
    <%= link_to "Home", "/" %>
    <% if logged_in? %>
      <%= link_to "Profile", @user %>
      <%= link_to "Log Out", sessions_path, method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_path %>
      <%= link_to "Log In", new_session_path %>
    <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Hey look it's working</h1>
<%= link_to "Lookit all these decks", decks_path %>

app/views/pages/session_helper.html.erb
<p><%= @uniqueword22 %></p>

app/views/rounds/new.html.erb
<h1><%= card.question %></h1>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@user.errors.count, "error") %> prevented this user from saving.</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

  <%= render 'form' %>

app/views/users/new.html.erb
<h1>Register!</h1>

  <%= render 'form' %>

app/views/users/show.html.erb
<h1>
  Hi, <%= @user.email %>
</h1>